// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/core/common/services/database/dto/secrets_dto.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 6547438553722868163),
      name: 'SecretsDTO',
      lastPropertyId: const obx_int.IdUid(5, 8872541514302923873),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4006209659351168875),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 9033878377737889133),
            name: 'secretType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2871767169339378926),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7310811044181557528),
            name: 'modifiedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8872541514302923873),
            name: 'content',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 6547438553722868163),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [8704140309286713244],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        7883627629428211506,
        8485094960723839073,
        603726306708849704,
        2855135165893480894,
        2180263731674156849,
        9086830017222490181,
        5793042775041285037,
        5808013804863688965
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    SecretsDTO: obx_int.EntityDefinition<SecretsDTO>(
        model: _entities[0],
        toOneRelations: (SecretsDTO object) => [],
        toManyRelations: (SecretsDTO object) => {},
        getId: (SecretsDTO object) => object.id,
        setId: (SecretsDTO object, int id) {
          object.id = id;
        },
        objectToFB: (SecretsDTO object, fb.Builder fbb) {
          final secretTypeOffset = fbb.writeString(object.secretType);
          final contentOffset = fbb.writeString(object.content);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, secretTypeOffset);
          fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(3, object.modifiedAt?.millisecondsSinceEpoch);
          fbb.addOffset(4, contentOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final modifiedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final secretTypeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final modifiedAtParam = modifiedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(modifiedAtValue);
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final object = SecretsDTO(
              id: idParam,
              secretType: secretTypeParam,
              createdAt: createdAtParam,
              modifiedAt: modifiedAtParam,
              content: contentParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SecretsDTO] entity fields to define ObjectBox queries.
class SecretsDTO_ {
  /// see [SecretsDTO.id]
  static final id =
      obx.QueryIntegerProperty<SecretsDTO>(_entities[0].properties[0]);

  /// see [SecretsDTO.secretType]
  static final secretType =
      obx.QueryStringProperty<SecretsDTO>(_entities[0].properties[1]);

  /// see [SecretsDTO.createdAt]
  static final createdAt =
      obx.QueryDateProperty<SecretsDTO>(_entities[0].properties[2]);

  /// see [SecretsDTO.modifiedAt]
  static final modifiedAt =
      obx.QueryDateProperty<SecretsDTO>(_entities[0].properties[3]);

  /// see [SecretsDTO.content]
  static final content =
      obx.QueryStringProperty<SecretsDTO>(_entities[0].properties[4]);
}
